### ISSUE TITLE
Fetching Data Through API

### ISSUE THREAD

**Issue by Eylexander** [Eylexander/Project-2B#1]
Hey @dannyhpy ! J'ai aucune idée de ton niveau en Web, mais je sais que tu assures en JavaScript. Je fais face à un problème, par soucis d'optimisation je me suis fixé comme objectif de faire venir des informations de ma page depuis une API (celle de Github).
En effet, sur ma page, je présente mes différents projets sous forme de PortFolio, et j'ai essayé de faire venir les descriptions directement depuis Github, voici mon code : 
```
<script type="text/JavaScript" src="http://code.jquery.com/jquery-latest.min.js">
  var content = document.body.querySelector("#ah");
  $(document).get("https://api.github.com/repos/Eylexander/Project-1B", function(result) {
    content.value = result.description;
});
</script>
<p id="ah"></p>
```

Mais rien à faire, j'ai fait mes recherches, et ce code devrait marcher. Merci d'avance pour ton expertise.

**Comment by dannyhpy** [comment]
Ta balise `script` contient un attribut `src` qui est **prioritaire** sur le _contenu du script_.
Autrement dit, il importe _jQuery_ puis il s'arrête.

<hr>

Fais en deux temps

```html
<script type="text/JavaScript" src="http://code.jquery.com/jquery-latest.min.js"></script>
<script>
  var content = document.body.querySelector("#ah");
  $(document).get("https://api.github.com/repos/Eylexander/Project-1B", function(result) {
    content.value = result.description;
});
</script>
<p id="ah"></p>

**Comment by Eylexander** [comment]
J'avais déjà essayé comme ça auparavant, mais toujours rien à faire (je ne connaissais pas la priorité de la balise).
Je pense que le soucis vient vraiment de la communication avec l'API, parce que dans l'analyse réseau du chargement de la page, aucune requête n'est envoyé.

**Comment by dannyhpy** [comment]
Effectivement, j'ai pas fait attention au reste du code

Le problème venait de **$(document).get**

(Mais je ne serais pas expliquer précisément pourquoi, j'y connais pas grand chose à jQuery)

<hr>

```html
<p id="ah"></p>
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
<script>
  var content = $("#ah");
  $.get("https://api.github.com/repos/Eylexander/Project-1B", function(result) {
    content.append(JSON.stringify(result));
  });
</script>
```

**Comment by Eylexander** [comment]
Tout marche beaucoup mieux, merci !
